package org.credess.model.validator;
/**
 * Interface for the Triple Green Light validation cascade (Section 4.2).
 * Each barrier must be passed sequentially.
 */
public interface ValidationBarrier {

    /**
     * Validates the generated artifact.
     *
     * @param artifact The code or text artifact generated by the agent.
     * @return ValidationResult containing pass/fail status and quality metrics.
     */
    ValidationResult validate(String artifact);
}